name: ImaginearsCore
author: Gatario
main: club.imaginears.core.Core
version: [0.1-BETA]
description: Created for ImaginearsClub
api-version: 1.13
commands:
  edituser:
  fly:
  vanish:
    aliases: [v, va]
  vanished:
    aliases: [vlist, vanishedlist]
  nightvision:
    aliases: [nv]
  teleport:
    aliases: [tp]
  teleporthere:
    aliases: [tphere]
  setwarp:
  delwarp:
  warp:
  warps:
permissions:
  core.edituser:
  core.updaterank:
  core.fly:
  core.flyothers:
  core.all:
  core.vanish:
  core.vanishothers:
  core.nv:
  core.nvothers:
  core.staff:
  core.tp:
  core.tpothers:
  core.tphere:
  core.setwarp:
  core.delwarp:
  core.warps:
  core.warps.guest:
  core.warps.silver:
  core.warps.gold:
  core.warps.platinum:
  core.warps.platinum+:
  core.warps.specialguest:
  core.warps.security:
  core.warps.character:
  core.warps.photopass:
  core.warps.castmember:
  core.warps.coordinator:
  core.warps.developer:
  core.warps.manager:
